import 'package:flutter/material.dart';
import 'dart:async';

void main() {
  runApp(const AzelingoApp());
}

// --- Qlobal Sözlük Meneceri ---
ValueNotifier<List<Map<String, String>>> learnedWordsNotifier = ValueNotifier(
  [],
);

class AzelingoApp extends StatelessWidget {
  const AzelingoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Azelingo',
      theme: ThemeData(
        brightness: Brightness.dark,
        useMaterial3: true,
        primaryColor: const Color(0xFFD4AF37),
        scaffoldBackgroundColor: const Color(0xFF0A0A0A),
        fontFamily: 'Roboto',
      ),
      home: const MainNavigationHolder(),
    );
  }
}

// --- MODELLƏR ---
class Lesson {
  final String title;
  final String description;
  final IconData icon;
  final List<Color> gradient;
  final String difficulty;
  final List<Map<String, dynamic>> questions;

  Lesson({
    required this.title,
    required this.description,
    required this.icon,
    required this.gradient,
    required this.difficulty,
    required this.questions,
  });
}

// --- NAVİQASİYA ---
class MainNavigationHolder extends StatefulWidget {
  const MainNavigationHolder({super.key});

  @override
  State<MainNavigationHolder> createState() => _MainNavigationHolderState();
}

class _MainNavigationHolderState extends State<MainNavigationHolder> {
  int _selectedIndex = 0;
  final List<Widget> _screens = [
    const HomeScreen(),
    const LearnedWordsScreen(),
    const ProfileScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(index: _selectedIndex, children: _screens),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _selectedIndex,
        onTap: (index) => setState(() => _selectedIndex = index),
        backgroundColor: const Color(0xFF151515),
        selectedItemColor: const Color(0xFFD4AF37),
        unselectedItemColor: Colors.grey.shade600,
        type: BottomNavigationBarType.fixed,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.bolt_rounded),
            label: 'Öğren',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.auto_stories_rounded),
            label: 'Sözlük',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.favorite_rounded),
            label: 'Esma',
          ),
        ],
      ),
    );
  }
}

// --- ANA EKRAN (TAM 30 KATEQORİYA) ---
class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  late List<Lesson> allLessons;

  @override
  void initState() {
    super.initState();
    allLessons = [
      // --- KOLAY (10) ---
      _createFullLesson(
        "Tanışlıq",
        "Selamlaşma ve Tanışma",
        Icons.handshake,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Salam",
          "Necəsən?",
          "Adın nədir?",
          "Sağ ol",
          "Sabahın xeyir",
          "Axşamın xeyir",
          "Gecən xeyrə",
          "Buyur",
          "Xoş gəldin",
          "Görüşənədək",
          "Bəli",
          "Xeyr",
          "Zəhmət olmasa",
          "Bağışlayın",
          "Necəsiniz?",
          "Haralısan?",
          "Yaxşıyam",
          "Pissən?",
          "Məmnun oldum",
          "Təbrik edirəm",
        ],
        [
          "Merhaba",
          "Nasılsın?",
          "Adın ne?",
          "Teşekkürler",
          "Günaydın",
          "İyi akşamlar",
          "İyi geceler",
          "Buyur",
          "Hoş geldin",
          "Görüşmek üzere",
          "Evet",
          "Hayır",
          "Lütfen",
          "Affedersiniz",
          "Nasılsınız?",
          "Nerelisin?",
          "İyiyim",
          "Kötü müsün?",
          "Memnun oldum",
          "Tebrik ederim",
        ],
      ),

      _createFullLesson(
        "Rənglər",
        "Renklerin Dünyası",
        Icons.palette,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Qırmızı",
          "Mavi",
          "Yaşıl",
          "Sarı",
          "Qara",
          "Ağ",
          "Narıncı",
          "Bənövşəyi",
          "Çəhrayı",
          "Boz",
          "Qəhvəyi",
          "Gümüşü",
          "Qızılı",
          "Tünd göy",
          "Açıq mavi",
          "Şəffaf",
          "Parlaq",
          "Mat",
          "Rəngarəng",
          "Tünd",
        ],
        [
          "Kırmızı",
          "Mavi",
          "Yeşil",
          "Sarı",
          "Siyah",
          "Beyaz",
          "Turuncu",
          "Mor",
          "Pembe",
          "Gri",
          "Kahverengi",
          "Gümüş rengi",
          "Altın rengi",
          "Lacivert",
          "Açık mavi",
          "Şeffaf",
          "Parlak",
          "Mat",
          "Rengarenk",
          "Koyu",
        ],
      ),

      _createFullLesson(
        "Rəqəmlər",
        "Sayılar ve Sayma",
        Icons.looks_one,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Bir",
          "İki",
          "Üç",
          "Dörd",
          "Beş",
          "Altı",
          "Yeddi",
          "Səkkiz",
          "Doqquz",
          "On",
          "On bir",
          "İyirmi",
          "Otuz",
          "Qırx",
          "Əlli",
          "Altmış",
          "Yetmiş",
          "Səksən",
          "Doxsan",
          "Yüz",
        ],
        [
          "Bir",
          "İki",
          "Üç",
          "Dört",
          "Beş",
          "Altı",
          "Yedi",
          "Sekiz",
          "Dokuz",
          "On",
          "On bir",
          "Yirmi",
          "Otuz",
          "Kırk",
          "Elli",
          "Altmış",
          "Yetmiş",
          "Seksen",
          "Doksan",
          "Yüz",
        ],
      ),

      _createFullLesson(
        "Ailə",
        "Aile Bireyleri",
        Icons.family_restroom,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Ana",
          "Ata",
          "Bacı",
          "Qardaş",
          "Nənə",
          "Baba",
          "Xala",
          "Bibi",
          "Əmi",
          "Dayı",
          "Oğul",
          "Qız",
          "Uşaq",
          "Həyat yoldaşı",
          "Qohum",
          "Gəlin",
          "Bəy",
          "Nəvə",
          "Qardaşı oğlu",
          "Bacı qızı",
        ],
        [
          "Anne",
          "Baba",
          "Kız kardeş",
          "Erkek kardeş",
          "Nine",
          "Dede",
          "Teyze",
          "Hala",
          "Amca",
          "Dayı",
          "Oğul",
          "Kız",
          "Çocuk",
          "Eş",
          "Akraba",
          "Gelin",
          "Damat",
          "Torun",
          "Yeğen (E)",
          "Yeğen (K)",
        ],
      ),

      _createFullLesson(
        "Meyvələr",
        "Meyveler ve Sebzeler",
        Icons.apple,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Alma",
          "Armud",
          "Heyva",
          "Nar",
          "Üzüm",
          "Gilas",
          "Çiyələk",
          "Qarpız",
          "Yemiş",
          "Şaftalı",
          "Pomidor",
          "Xiyar",
          "Kartof",
          "Soğan",
          "Sarımsaq",
          "Kök",
          "Bibər",
          "Badımcan",
          "Qabaq",
          "Göyərti",
        ],
        [
          "Elma",
          "Armut",
          "Ayva",
          "Nar",
          "Üzüm",
          "Kiraz",
          "Çilek",
          "Karpuz",
          "Kavun",
          "Şeftali",
          "Domates",
          "Salatalık",
          "Patates",
          "Soğan",
          "Sarımsak",
          "Havuç",
          "Biber",
          "Patlıcan",
          "Kabak",
          "Yeşillik",
        ],
      ),

      _createFullLesson(
        "Heyvanlar",
        "Sevimli Dostlarımız",
        Icons.pets,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "İt",
          "Pişik",
          "At",
          "İnək",
          "Qoyun",
          "Keçi",
          "Toyuq",
          "Xoruz",
          "Ördək",
          "Qaz",
          "Şir",
          "Pələng",
          "Ayı",
          "Canavar",
          "Tülkü",
          "Dovşan",
          "Siçan",
          "İlan",
          "Balıq",
          "Quş",
        ],
        [
          "Köpek",
          "Kedi",
          "At",
          "İnek",
          "Koyun",
          "Keçi",
          "Tavuk",
          "Horoz",
          "Ördek",
          "Kaz",
          "Aslan",
          "Kaplan",
          "Ayı",
          "Kurt",
          "Tilki",
          "Tavşan",
          "Fare",
          "Yılan",
          "Balık",
          "Kuş",
        ],
      ),

      _createFullLesson(
        "Geyim",
        "Kıyafetler ve Moda",
        Icons.checkroom,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Köynək",
          "Şalvar",
          "Don",
          "Eynək",
          "Ayaqqabı",
          "Papaq",
          "Əlcək",
          "Şərf",
          "Paltar",
          "Yubka",
          "Corab",
          "Kəmər",
          "Çanta",
          "Saat",
          "Üzük",
          "Sırğa",
          "Boyunbağı",
          "Pencək",
          "Palto",
          "Çətir",
        ],
        [
          "Gömlek",
          "Pantolon",
          "Elbise",
          "Gözlük",
          "Ayakkabı",
          "Şapka",
          "Eldiven",
          "Atkı",
          "Giysi",
          "Etek",
          "Çorap",
          "Kemer",
          "Çanta",
          "Saat",
          "Yüzük",
          "Küpe",
          "Kolye",
          "Ceket",
          "Palto",
          "Şemsiye",
        ],
      ),

      _createFullLesson(
        "Məktəb",
        "Eğitim ve Okul",
        Icons.school,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Kitab",
          "Dəftər",
          "Qələm",
          "Pozan",
          "Xətkeş",
          "Müəllim",
          "Şagird",
          "Tələbə",
          "Sinif",
          "Dərs",
          "Məktəb",
          "Universitet",
          "İmtahan",
          "Qiymət",
          "Lüğət",
          "Xəritə",
          "Çanta",
          "Parta",
          "Yazı taxtası",
          "Təbaşir",
        ],
        [
          "Kitap",
          "Defter",
          "Kalem",
          "Silgi",
          "Cetvel",
          "Öğretmen",
          "Öğrenci",
          "Üniversite öğrencisi",
          "Sınıf",
          "Ders",
          "Okul",
          "Üniversite",
          "Sınav",
          "Not/Puan",
          "Sözlük",
          "Harita",
          "Çanta",
          "Sıra",
          "Yazı tahtası",
          "Tebeşir",
        ],
      ),

      _createFullLesson(
        "Günlər",
        "Günler ve Aylar",
        Icons.calendar_today,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Bazar ertəsi",
          "Çərşənbə axşamı",
          "Çərşənbə",
          "Cümə axşamı",
          "Cümə",
          "Şənbə",
          "Bazar",
          "Yanvar",
          "Fevral",
          "Mart",
          "Aprel",
          "May",
          "İyun",
          "İyul",
          "Avqust",
          "Sentyabr",
          "Oktyabr",
          "Noyabr",
          "Dekabr",
          "Təqvim",
        ],
        [
          "Pazartesi",
          "Salı",
          "Çarşamba",
          "Perşembe",
          "Cuma",
          "Cumartesi",
          "Pazar",
          "Ocak",
          "Şubat",
          "Mart",
          "Nisan",
          "Mayıs",
          "Haziran",
          "Temmuz",
          "Ağustos",
          "Eylül",
          "Ekim",
          "Kasım",
          "Aralık",
          "Takvim",
        ],
      ),

      _createFullLesson(
        "Bədən",
        "Vücudumuz",
        Icons.person_outline,
        [const Color(0xFF2ECC71), const Color(0xFF27AE60)],
        "KOLAY",
        [
          "Baş",
          "Üz",
          "Göz",
          "Burun",
          "Ağız",
          "Qulaq",
          "Diş",
          "Dil",
          "Saç",
          "Əl",
          "Ayaq",
          "Barmaq",
          "Qol",
          "Ürək",
          "Qarın",
          "Bel",
          "Diz",
          "Dəri",
          "Sümük",
          "Qan",
        ],
        [
          "Baş",
          "Yüz",
          "Göz",
          "Burun",
          "Ağız",
          "Kulak",
          "Diş",
          "Dil",
          "Saç",
          "El",
          "Ayak",
          "Parmak",
          "Kol",
          "Kalp",
          "Karın",
          "Bel",
          "Diz",
          "Deri",
          "Kemik",
          "Kan",
        ],
      ),

      // --- ORTA (10) ---
      _createFullLesson(
        "Restoran",
        "Yemek ve Sipariş",
        Icons.restaurant,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Menyu",
          "Sifariş",
          "Xörək",
          "İçki",
          "Su",
          "Çörək",
          "Duz",
          "İstiot",
          "Şəkər",
          "Çay",
          "Qəhvə",
          "Süfrə",
          "Qaşıq",
          "Vilka",
          "Bıçaq",
          "Boşqab",
          "Stəkan",
          "Hesab",
          "Ofisiant",
          "Dadlı",
        ],
        [
          "Menü",
          "Sipariş",
          "Yemek",
          "İçecek",
          "Su",
          "Ekmek",
          "Tuz",
          "Biber",
          "Şeker",
          "Çay",
          "Kahve",
          "Sofra",
          "Kaşık",
          "Çatal",
          "Bıçak",
          "Tabak",
          "Bardak",
          "Hesap",
          "Garson",
          "Lezzetli",
        ],
      ),

      _createFullLesson(
        "Duyğular",
        "Duygular ve Hisler",
        Icons.favorite,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Sevgi",
          "Nifrət",
          "Xoşbəxtlik",
          "Kədər",
          "Qorxu",
          "Təəccüb",
          "Qəzəb",
          "Şadlıq",
          "Ümid",
          "İnam",
          "Həsrət",
          "Darxmaq",
          "Gülmək",
          "Ağlamaq",
          "Sevinmək",
          "Kədərlənmək",
          "Qorxmaq",
          "İnanmaq",
          "Sevmək",
          "Gözləmək",
        ],
        [
          "Sevgi",
          "Nefret",
          "Mutluluk",
          "Keder",
          "Korku",
          "Şaşkınlık",
          "Öfke",
          "Sevinç",
          "Umut",
          "İnanç",
          "Hasret",
          "Özlemek",
          "Gülmek",
          "Ağlamak",
          "Sevinmek",
          "Üzülmek",
          "Korkmak",
          "İnanmak",
          "Sevmek",
          "Beklemek",
        ],
      ),

      _createFullLesson(
        "Hava",
        "Hava Durumu",
        Icons.cloud,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Günəş",
          "Bulud",
          "Yağış",
          "Qar",
          "Külək",
          "Tufan",
          "Şimşək",
          "Göy qurşağı",
          "İsti",
          "Soyuq",
          "Mülayim",
          "Rütubət",
          "Duman",
          "Dolu",
          "Səma",
          "Ulduz",
          "Ay",
          "İqlim",
          "Dərəə",
          "Proqnoz",
        ],
        [
          "Güneş",
          "Bulud",
          "Yağmur",
          "Kar",
          "Rüzgar",
          "Fırtına",
          "Şimşek",
          "Gökkuşağı",
          "Sıcak",
          "Soğuk",
          "Ilıman",
          "Nem",
          "Sis",
          "Dolu",
          "Gökyüzü",
          "Yıldız",
          "Ay",
          "İklim",
          "Derece",
          "Tahmin",
        ],
      ),

      _createFullLesson(
        "Səyahət",
        "Tatil ve Gezi",
        Icons.flight,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Səfər",
          "Bilet",
          "Pasport",
          "Viza",
          "Otul",
          "Hava limanı",
          "Təyyarə",
          "Qatar",
          "Gəmi",
          "Avtobus",
          "Baqaj",
          "Ekskursiya",
          "Muzey",
          "Dəniz",
          "Çimərlik",
          "Dağ",
          "Meşə",
          "Xəritə",
          "Bələdçi",
          "Xarici",
        ],
        [
          "Yolculuk",
          "Bilet",
          "Pasaport",
          "Vize",
          "Otel",
          "Havalimanı",
          "Uçak",
          "Tren",
          "Gemi",
          "Otobüs",
          "Bagaj",
          "Gezi",
          "Müze",
          "Deniz",
          "Plaj",
          "Dağ",
          "Orman",
          "Harita",
          "Rehber",
          "Yabancı",
        ],
      ),

      _createFullLesson(
        "Peşələr",
        "Meslekler",
        Icons.work,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Həkim",
          "Müəllim",
          "Mühəndis",
          "Sürücü",
          "Aşpaz",
          "Polis",
          "Əsgər",
          "Yazıçı",
          "Rəssam",
          "Musiqiçi",
          "Aktyor",
          "Satıcı",
          "Fəhlə",
          "Dərzi",
          "Bərbər",
          "Vəkil",
          "Jurnalist",
          "Pilot",
          "Dənizçi",
          "Sahibkar",
        ],
        [
          "Doktor",
          "Öğretmen",
          "Mühendis",
          "Sürücü",
          "Aşçı",
          "Polis",
          "Asker",
          "Yazar",
          "Ressam",
          "Müzisyen",
          "Aktör",
          "Satıcı",
          "İşçi",
          "Terzi",
          "Berber",
          "Avukat",
          "Gazeteci",
          "Pilot",
          "Denizci",
          "Girişimci",
        ],
      ),

      _createFullLesson(
        "Şəhər",
        "Şehir Hayatı",
        Icons.location_city,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Küçə",
          "Meydan",
          "Park",
          "Bina",
          "Mənzil",
          "Mərkəz",
          "Mağaza",
          "Bazar",
          "Aptek",
          "Xəstəxana",
          "Bank",
          "Poçt",
          "Dayanacaq",
          "Metro",
          "Körpü",
          "Yol",
          "İşıqfor",
          "Abidə",
          "Teatr",
          "Kino",
        ],
        [
          "Sokak",
          "Meydan",
          "Park",
          "Bina",
          "Daire",
          "Merkez",
          "Mağaza",
          "Pazar",
          "Eczane",
          "Hastane",
          "Banka",
          "Postane",
          "Durak",
          "Metro",
          "Köprü",
          "Yol",
          "Trafik ışığı",
          "Anıt",
          "Tiyatr",
          "Sinema",
        ],
      ),

      _createFullLesson(
        "Ev",
        "Ev Eşyaları",
        Icons.home,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Qapı",
          "Pəncərə",
          "Divar",
          "Döşəmə",
          "Tavan",
          "Otaq",
          "Qonaq otağı",
          "Yataq otağı",
          "Mətbəx",
          "Hamam",
          "Mebel",
          "Masa",
          "Stul",
          "Divan",
          "Yataq",
          "Şkaf",
          "Xalça",
          "Pərdə",
          "Güzgü",
          "Lampa",
        ],
        [
          "Kapı",
          "Pencere",
          "Duvar",
          "Yer/Zemin",
          "Tavan",
          "Oda",
          "Oturma odası",
          "Yatak odası",
          "Mutfak",
          "Banyo",
          "Mobilya",
          "Masa",
          "Sandalye",
          "Kanepe",
          "Yatak",
          "Dolap",
          "Halı",
          "Perde",
          "Ayna",
          "Lamba",
        ],
      ),

      _createFullLesson(
        "Nəqliyyat",
        "Ulaşım Araçları",
        Icons.directions_bus,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Avtomobil",
          "Maşın",
          "Velosiped",
          "Motosiklet",
          "Taksi",
          "Tramvay",
          "Trolleybus",
          "Yük maşını",
          "Yanğınsöndürən",
          "Təcili yardım",
          "Sükan",
          "Təkər",
          "Mühərrik",
          "Benzin",
          "Yol",
          "Sürət",
          "Dayanacaq",
          "Sürücü",
          "Sərnişin",
          "Yolçu",
        ],
        [
          "Otomobil",
          "Araba",
          "Bisiklet",
          "Motosiklet",
          "Taksi",
          "Tramvay",
          "Troleybüs",
          "Kamyon",
          "İtfaiye",
          "Ambulans",
          "Direksiyon",
          "Tekerlek",
          "Motor",
          "Benzin",
          "Yol",
          "Hız",
          "Durak",
          "Sürücü",
          "Yolcu",
          "Yolcu",
        ],
      ),

      _createFullLesson(
        "Hobbilər",
        "Hobiler ve Eğlence",
        Icons.sports_esports,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Musiqi",
          "Rəqs",
          "İdman",
          "Futbol",
          "Şahmat",
          "Kitab oxumaq",
          "Şəkil çəkmək",
          "Səyahət etmək",
          "Üzmək",
          "Balıq tutmaq",
          "Kino",
          "Teatr",
          "Konsert",
          "Oyun",
          "Kompüter oyunları",
          "İnternet",
          "Fotoqrafiya",
          "Yemək bişirmək",
          "Bağçılıq",
          "Kolleksiya",
        ],
        [
          "Müzik",
          "Dans",
          "Spor",
          "Futbol",
          "Satranç",
          "Kitap okumak",
          "Resim çizmek",
          "Seyahat etmek",
          "Yüzmek",
          "Balık tutmak",
          "Sinema",
          "Tiyatro",
          "Konser",
          "Oyun",
          "Bilgisayar oyunları",
          "İnternet",
          "Fotoğrafçılık",
          "Yemek pişirmek",
          "Bahçıvanlık",
          "Koleksiyon",
        ],
      ),

      _createFullLesson(
        "Sağlamlıq",
        "Sağlık ve Hastane",
        Icons.medical_services,
        [const Color(0xFFF1C40F), const Color(0xFFF39C12)],
        "ORTA",
        [
          "Ağrı",
          "Xəstəlik",
          "Qızdırma",
          "Öskürək",
          "Zökəm",
          "Dərman",
          "Resept",
          "İnyeksiya",
          "Əməliyyat",
          "Həkim",
          "Tibb bacısı",
          "Xəstəxana",
          "Aptek",
          "Təcili yardım",
          "Qan təzyiqi",
          "Vitamin",
          "Sağlamlıq",
          "Pəhriz",
          "İdman",
          "Yuxu",
        ],
        [
          "Ağrı",
          "Hastalık",
          "Ateş",
          "Öksürük",
          "Nezle",
          "İlaç",
          "Reçete",
          "Enjeksiyon",
          "Ameliyat",
          "Doktor",
          "Hemşire",
          "Hastane",
          "Eczane",
          "Ambulans",
          "Kan basıncı",
          "Vitamin",
          "Sağlık",
          "Diyet",
          "Spor",
          "Uyku",
        ],
      ),

      // --- ZOR (10) ---
      _createFullLesson(
        "Zamanlar",
        "Gramer ve Zamanlar",
        Icons.history,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "İndiki zaman",
          "Keçmiş zaman",
          "Gələcək zaman",
          "Dünən",
          "Bu gün",
          "Sabah",
          "İndi",
          "Həmişə",
          "Heç vaxt",
          "Tez-tez",
          "Bəzən",
          "Hər gün",
          "Hər həftə",
          "Hər ay",
          "Hər il",
          "Əvvəl",
          "Sonra",
          "Səhər",
          "Günorta",
          "Axşam",
        ],
        [
          "Şimdiki zaman",
          "Geçmiş zaman",
          "Gelecek zaman",
          "Dün",
          "Bugün",
          "Yarın",
          "Şimdi",
          "Her zaman",
          "Asla",
          "Sık sık",
          "Bazen",
          "Her gün",
          "Her hafta",
          "Her ay",
          "Her yıl",
          "Önce",
          "Sonra",
          "Sabah",
          "Öğle",
          "Akşam",
        ],
      ),

      _createFullLesson(
        "Siyasət",
        "Politika ve Devlet",
        Icons.gavel,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Dövlət",
          "Prezident",
          "Nazir",
          "Parlament",
          "Qanun",
          "Seçki",
          "Səsvermə",
          "Partiya",
          "Siyasət",
          "Hökumət",
          "Azadlıq",
          "Hüquq",
          "Demokratiya",
          "Respublika",
          "Vətəndaş",
          "Xalq",
          "Sərhəd",
          "Ordu",
          "Müharibə",
          "Sülh",
        ],
        [
          "Devlet",
          "Cumhurbaşkanı",
          "Bakan",
          "Parlamento",
          "Kanun",
          "Seçim",
          "Oy verme",
          "Parti",
          "Siyaset",
          "Hükümet",
          "Özgürlük",
          "Hukuk",
          "Demokrasi",
          "Cumhuriyet",
          "Vatandaş",
          "Halk",
          "Sınır",
          "Ordu",
          "Savaş",
          "Barış",
        ],
      ),

      _createFullLesson(
        "İncəsənət",
        "Sanat ve Kültür",
        Icons.art_track,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Mədəniyyət",
          "İncəsənət",
          "Musiqi",
          "Rəsm",
          "Heykəltəraşlıq",
          "Memarlıq",
          "Ədəbiyyat",
          "Teatr",
          "Kino",
          "Rəqs",
          "Muzey",
          "Sərgi",
          "Qalereya",
          "İstedad",
          "Yaradıcılıq",
          "Əsər",
          "Müəllif",
          "Üslub",
          "Klassik",
          "Müasir",
        ],
        [
          "Kültür",
          "Sanat",
          "Müzik",
          "Resim",
          "Heykel",
          "Mimari",
          "Edebiyat",
          "Tiyatro",
          "Sinema",
          "Dans",
          "Müze",
          "Sergi",
          "Galeri",
          "Yetenek",
          "Yaratıcılık",
          "Eser",
          "Yazar/Müellif",
          "Üslup",
          "Klasik",
          "Modern",
        ],
      ),

      _createFullLesson(
        "Texnologiya",
        "Bilim ve Teknoloji",
        Icons.computer,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Kompüter",
          "İnternet",
          "Sayt",
          "Proqram",
          "Mobil telefon",
          "Rabitə",
          "Məlumat",
          "Texnika",
          "Elm",
          "Alim",
          "Kəşf",
          "İxtira",
          "Kosmos",
          "Raket",
          "Süni intellekt",
          "Robot",
          "Şəbəkə",
          "Təhlükəsizlik",
          "Ekran",
          "Klaviatura",
        ],
        [
          "Bilgisayar",
          "İnternet",
          "Site",
          "Program",
          "Cep telefonu",
          "İletişim",
          "Bilgi/Veri",
          "Teknik",
          "Bilim",
          "Bilim adamı",
          "Keşif",
          "İcat",
          "Uzay",
          "Roket",
          "Yapay zeka",
          "Robot",
          "Ağ",
          "Güvenlik",
          "Ekran",
          "Klavye",
        ],
      ),

      _createFullLesson(
        "Ədəbiyyat",
        "Edebiyat ve Şiir",
        Icons.auto_stories,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Kitab",
          "Yazıçı",
          "Şair",
          "Şeir",
          "Nəsr",
          "Roman",
          "Povest",
          "Hekayə",
          "Dram",
          "Komediya",
          "Faciə",
          "Qəhrəman",
          "Mövzu",
          "İdeya",
          "Süjet",
          "Təsvir",
          "Təşbeh",
          "Metafora",
          "Qafiye",
          "Misra",
        ],
        [
          "Kitap",
          "Yazar",
          "Şair",
          "Şiir",
          "Nesir",
          "Roman",
          "Uzun hikaye",
          "Hikaye",
          "Dram",
          "Komedi",
          "Trajedi",
          "Kahraman",
          "Konu",
          "Fikir/İdea",
          "Olay örgüsü",
          "Tasvir",
          "Benzetme",
          "Eğretileme",
          "Kafiye",
          "Mısra",
        ],
      ),

      _createFullLesson(
        "İqtisadiyyat",
        "Ekonomi ve Finans",
        Icons.attach_money,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "İqtisadiyyat",
          "Maliyyə",
          "Bank",
          "Pul",
          "Valyuta",
          "Məzənnə",
          "İnflyasiya",
          "Bazar",
          "Ticarət",
          "İdxal",
          "İxrac",
          "Sənaye",
          "Kənd təsərrüfatı",
          "Sahibkarlıq",
          "Gəlir",
          "Xərc",
          "Vergi",
          "Büdcə",
          "İnvestisiya",
          "Səhm",
        ],
        [
          "Ekonomi",
          "Finans",
          "Banka",
          "Para",
          "Döviz",
          "Kur",
          "Enflasyon",
          "Pazar",
          "Ticaret",
          "İthalat",
          "İhracat",
          "Sanayi",
          "Tarım",
          "Girişimcilik",
          "Gelir",
          "Gider",
          "Vergi",
          "Bütçe",
          "Yatırım",
          "Hisse senedi",
        ],
      ),

      _createFullLesson(
        "İdiomlar",
        "Deyimler ve Atasözleri",
        Icons.psychology,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Atalar sözü",
          "Məsəl",
          "İdiom",
          "Gözaydınlığı",
          "Xoşbəxt olmaq",
          "Başa düşmək",
          "Yola getmək",
          "Könlü açılmaq",
          "Ürəyi yanmaq",
          "Gözü qalmaq",
          "Dil tapmaq",
          "Əl tutmaq",
          "Yuxusu qaçmaq",
          "Burnu göynəmək",
          "Qulağına sırğa etmək",
          "Ağlına gəlmək",
          "Üzə çıxmaq",
          "Söz vermək",
          "Can qoymaq",
          "Hirsini tökmək",
        ],
        [
          "Atasözü",
          "Deyim",
          "İdiyom",
          "Göz aydınlığı",
          "Mutlu olmak",
          "Anlamak",
          "Geçinmek",
          "Gönlü açılmak",
          "İçi yanmak",
          "Gözü kalmak",
          "Dil bulmak",
          "Yardım etmek",
          "Uykusu kaçmak",
          "Burnu sızlamak",
          "Kulağına küpe etmek",
          "Aklına gelmek",
          "Ortaya çıkmak",
          "Söz vermek",
          "Emek vermek",
          "Hırsını boşaltmak",
        ],
      ),

      _createFullLesson(
        "Fəlsəfə",
        "Düşünce ve Mantık",
        Icons.lightbulb,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Fəlsəfə",
          "Düşüncə",
          "Məntiq",
          "Həqiqət",
          "Varlıq",
          "Zaman",
          "Məkan",
          "Ruh",
          "Maddi",
          "Mənəvi",
          "Əxlaq",
          "Xeyir",
          "Şər",
          "Ədalət",
          "Azadlıq",
          "Məna",
          "Həyat",
          "Ölüm",
          "Bilik",
          "İdrak",
        ],
        [
          "Felsefe",
          "Düşünce",
          "Mantık",
          "Gerçek",
          "Varlık",
          "Zaman",
          "Mekan",
          "Ruh",
          "Maddi",
          "Manevi",
          "Ahlak",
          "Hayır",
          "Şer",
          "Adalet",
          "Özgürlük",
          "Anlam",
          "Hayat",
          "Ölüm",
          "Bilgi",
          "İdrak",
        ],
      ),

      _createFullLesson(
        "Təbiət",
        "Çevre ve Ekoloji",
        Icons.nature_people,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Təbiət",
          "Ətraf mühit",
          "Ekologiya",
          "Meşə",
          "Dağ",
          "Çay",
          "Göl",
          "Dəniz",
          "Okean",
          "Səhra",
          "Hava",
          "Torpaq",
          "Su",
          "Bitki",
          "Heyvan",
          "İqlim dəyişikliyi",
          "Çirklənmə",
          "Qorumaq",
          "Təmizlik",
          "Enerji",
        ],
        [
          "Doğa",
          "Çevre",
          "Ekoloji",
          "Orman",
          "Dağ",
          "Nehir",
          "Göl",
          "Deniz",
          "Okyanus",
          "Çöl",
          "Hava",
          "Toprak",
          "Su",
          "Bitki",
          "Hayvan",
          "İklim değişikliği",
          "Kirlilik",
          "Korumak",
          "Temizlik",
          "Enerji",
        ],
      ),

      _createFullLesson(
        "Hüquq",
        "Hukuk ve Adalet",
        Icons.balance,
        [const Color(0xFFE74C3C), const Color(0xFFC0392B)],
        "ZOR",
        [
          "Hüquq",
          "Qanun",
          "Ədalət",
          "Məhkəmə",
          "Hakim",
          "Vəkil",
          "Prokuror",
          "Cinayət",
          "Cəza",
          "Həbs",
          "Vətəndaşlıq",
          "Sənəd",
          "Müqavilə",
          "Şahid",
          "Sübut",
          "İnsan hüquqları",
          "Azadlıq",
          "Məsuliyyət",
          "Qayda",
          "Dövlət",
        ],
        [
          "Hukuk",
          "Kanun",
          "Adalet",
          "Mahkeme",
          "Hakim",
          "Avukat",
          "Savcı",
          "Suç",
          "Ceza",
          "Hapis",
          "Vatandaşlık",
          "Belge",
          "Sözleşme",
          "Şahit",
          "Kanıt",
          "İnsan hakları",
          "Özgürlük",
          "Sorumluluk",
          "Kural",
          "Devlet",
        ],
      ),
    ];
  }

  static Lesson _createFullLesson(
    String title,
    String desc,
    IconData icon,
    List<Color> colors,
    String diff,
    List<String> az,
    List<String> tr,
  ) {
    return Lesson(
      title: title,
      description: desc,
      icon: icon,
      gradient: colors,
      difficulty: diff,
      questions: List.generate(
        20,
        (i) => {
          "q": az[i],
          "tr": tr[i],
          "wrong": [tr[(i + 1) % 20], tr[(i + 2) % 20]],
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "AZELİNGO",
          style: TextStyle(
            fontWeight: FontWeight.w900,
            color: Color(0xFFD4AF37),
          ),
        ),
        centerTitle: true,
        backgroundColor: Colors.transparent,
      ),
      body: ListView.builder(
        padding: const EdgeInsets.all(20),
        itemCount: allLessons.length,
        itemBuilder: (context, index) => _buildCard(context, allLessons[index]),
      ),
    );
  }

  Widget _buildCard(BuildContext context, Lesson lesson) {
    return GestureDetector(
      onTap: () => Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => QuizScreen(lesson: lesson)),
      ),
      child: Container(
        margin: const EdgeInsets.only(bottom: 20),
        padding: const EdgeInsets.all(22),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30),
          gradient: LinearGradient(colors: lesson.gradient),
          boxShadow: [
            BoxShadow(
              color: lesson.gradient[0].withValues(alpha: 0.3),
              blurRadius: 15,
              offset: const Offset(0, 8),
            ),
          ],
        ),
        child: Row(
          children: [
            Icon(lesson.icon, size: 40, color: Colors.white),
            const SizedBox(width: 20),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    lesson.difficulty,
                    style: const TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      color: Colors.white70,
                    ),
                  ),
                  Text(
                    lesson.title,
                    style: const TextStyle(
                      fontSize: 22,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    lesson.description,
                    style: const TextStyle(fontSize: 13, color: Colors.white70),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// --- QUIZ EKRANI ---
class QuizScreen extends StatefulWidget {
  final Lesson lesson;
  const QuizScreen({super.key, required this.lesson});

  @override
  State<QuizScreen> createState() => _QuizScreenState();
}

class _QuizScreenState extends State<QuizScreen> {
  int _currentIdx = 0;
  int? _selectedIdx;
  bool? _isCorrect;
  List<String> _shuffledOptions = [];

  @override
  void initState() {
    super.initState();
    _loadQuestion();
  }

  void _loadQuestion() {
    var q = widget.lesson.questions[_currentIdx];
    _shuffledOptions = [q['tr'], ...q['wrong']];
    _shuffledOptions.shuffle();
    _selectedIdx = null;
    _isCorrect = null;
  }

  void _handleAnswer(int i) {
    if (_selectedIdx != null) return;

    String selectedText = _shuffledOptions[i];
    String correctText = widget.lesson.questions[_currentIdx]['tr'];
    String qText = widget.lesson.questions[_currentIdx]['q'];

    setState(() {
      _selectedIdx = i;
      _isCorrect = (selectedText == correctText);
    });

    if (_isCorrect!) {
      bool exists = learnedWordsNotifier.value.any((e) => e['az'] == qText);
      if (!exists) {
        learnedWordsNotifier.value = [
          ...learnedWordsNotifier.value,
          {'az': qText, 'tr': correctText},
        ];
      }
    }

    Future.delayed(const Duration(milliseconds: 1000), () {
      if (_isCorrect!) {
        if (_currentIdx < widget.lesson.questions.length - 1) {
          setState(() {
            _currentIdx++;
            _loadQuestion();
          });
        } else {
          _finish();
        }
      } else {
        setState(() {
          _selectedIdx = null;
          _isCorrect = null;
        });
      }
    });
  }

  void _finish() {
    showModalBottomSheet(
      context: context,
      backgroundColor: const Color(0xFF151515),
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(40)),
      ),
      builder: (context) => Container(
        padding: const EdgeInsets.all(40),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.stars, size: 80, color: Color(0xFFD4AF37)),
            const SizedBox(height: 20),
            const Text(
              "Mükəmməlsən Esma! ❤️",
              style: TextStyle(fontSize: 26, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 30),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFFD4AF37),
                minimumSize: const Size(double.infinity, 60),
              ),
              onPressed: () {
                Navigator.pop(context);
                Navigator.pop(context);
              },
              child: const Text(
                "DAVAM ET",
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    var q = widget.lesson.questions[_currentIdx];
    return Scaffold(
      appBar: AppBar(title: Text("${_currentIdx + 1} / 20"), centerTitle: true),
      body: Padding(
        padding: const EdgeInsets.all(25),
        child: Column(
          children: [
            LinearProgressIndicator(
              value: (_currentIdx + 1) / 20,
              minHeight: 10,
              color: widget.lesson.gradient[0],
              backgroundColor: Colors.white10,
            ),
            const SizedBox(height: 50),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(40),
              decoration: BoxDecoration(
                color: const Color(0xFF151515),
                borderRadius: BorderRadius.circular(35),
                border: Border.all(color: Colors.white10),
              ),
              child: Text(
                q['q'],
                style: const TextStyle(
                  fontSize: 48,
                  fontWeight: FontWeight.w900,
                ),
                textAlign: TextAlign.center,
              ),
            ),
            const SizedBox(height: 40),
            Expanded(
              child: ListView.builder(
                itemCount: 3,
                itemBuilder: (context, i) => _option(i),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _option(int i) {
    bool sel = _selectedIdx == i;
    Color col = Colors.white10;
    if (sel) col = _isCorrect! ? Colors.greenAccent : Colors.redAccent;
    return GestureDetector(
      onTap: () => _handleAnswer(i),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 300),
        margin: const EdgeInsets.only(bottom: 20),
        padding: const EdgeInsets.all(22),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25),
          border: Border.all(color: col, width: 3),
        ),
        child: Text(
          _shuffledOptions[i],
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: sel ? col : Colors.white,
          ),
          textAlign: TextAlign.center,
        ),
      ),
    );
  }
}

// --- SÖZLÜK ---
class LearnedWordsScreen extends StatelessWidget {
  const LearnedWordsScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("SÖZLÜK"), centerTitle: true),
      body: ValueListenableBuilder(
        valueListenable: learnedWordsNotifier,
        builder: (context, List<Map<String, String>> words, _) {
          if (words.isEmpty)
            return const Center(child: Text("Hələ söz öyrənməmisən ❤️"));
          return ListView.builder(
            padding: const EdgeInsets.all(20),
            itemCount: words.length,
            itemBuilder: (context, i) => ListTile(
              title: Text(words[i]['az']!),
              subtitle: Text(words[i]['tr']!),
              trailing: const Icon(Icons.check, color: Colors.greenAccent),
            ),
          );
        },
      ),
    );
  }
}

// --- PROFİL ---
class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const CircleAvatar(
              radius: 70,
              backgroundColor: Colors.red,
              child: Icon(Icons.favorite, size: 70, color: Colors.white),
            ),
            const SizedBox(height: 25),
            const Text(
              "Esmanur ❤️",
              style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 40),
            ValueListenableBuilder(
              valueListenable: learnedWordsNotifier,
              builder: (context, List<Map<String, String>> words, _) => Text(
                "Öyrənilən Söz: ${words.length}",
                style: const TextStyle(fontSize: 20, color: Color(0xFFD4AF37)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
